### ISSUE TITLE
Chrome 插件被下架

### ISSUE THREAD

**Issue by wenyue** [EhTagTranslation/EhSyringe#10]
**描述问题**
chrome插件404错误
**相关网址**
https://chrome.google.com/webstore/detail/ehsyringe/mbhdcfeopadbmjnlbpcallmalcefnbbb

**Comment by xioxin** [comment]
你的网络无法访问Google 自行翻墙

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/64074968-b7d04400-cce4-11e9-901b-25902d9f9dd0.png)

**Comment by wenyue** [comment]
![image](https://user-images.githubusercontent.com/4454019/64074974-c3236f80-cce4-11e9-8c3d-73372e6aa0b8.png)
已经翻墙，能访问google，确实404错误。

**Comment by xioxin** [comment]
啥情况 
![image](https://user-images.githubusercontent.com/5716100/64075018-3cbb5d80-cce5-11e9-9499-584dc83db600.png)

**Comment by xioxin** [comment]
并不知道问题出在哪里, 插件下个版本不再内置数据吧

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/64075196-ca984800-cce7-11e9-958b-cd539868c6b8.png)

**Comment by wenyue** [comment]
可以放到百度网盘吗？手动添加plugin就行了。

**Comment by KANEMsbnb** [comment]
雖然3天過去了，我還是想問一下有辦法修復嗎

**Comment by Mapaler** [comment]
你可以开发者模式手动加载代码

**Comment by xioxin** [comment]
@OpportunityLiu  可以自动打包上传releases吗

**Comment by OpportunityLiu** [comment]
把dist文件夹打包成zip，然后扩展名改crx就可以吗？

**Comment by xioxin** [comment]
我看一下

**Comment by xioxin** [comment]
> 把dist文件夹打包成zip，然后扩展名改crx就可以吗？

你看一下 https://github.com/EhTagTranslation/EhSyringe/releases/tag/v1.2.1
这个crx下载下来能不能直接安装, 这是上架最后一个版本google签过名的
我这里可以直接安装, 打开扩展,拖进去

**Comment by xioxin** [comment]
我可能没有保存签名私钥, 或许再我工作电脑上. 明天找找. 或许可以自己签名

**Comment by xioxin** [comment]
并没有保存私钥

**Comment by Mapaler** [comment]
crx不是也可以解压吗，为什么release要单独放个zip

**Comment by xioxin** [comment]
> crx不是也可以解压吗，为什么release要单独放个zip

因为我先传了zip 后来找到的crx

**Comment by xioxin** [comment]
crx有些小白不知道可以解压

**Comment by Mapaler** [comment]
我用7-zip，把后缀名改成zip反而打不开，crx可以解压，奇怪。

**Comment by xioxin** [comment]
> 我用7-zip，把后缀名改成zip反而打不开，crx可以解压，奇怪。

https://crxdoc-zh.appspot.com/extensions/crx

crx是头信息被修改了的zip
可能是7z只针对crx做了兼容

**Comment by 1608637229** [comment]
管的这么宽吗。针对于什么网站也要管啊。外国看来审查也挺严格吗

**Comment by 1608637229** [comment]
我现在电脑关机重启再开这个插件会经常自动关闭。又要手动打开。目前浏览器用的是百分浏览器。有没有什么办法解决

**Comment by Mapaler** [comment]
火狐的还能用

**Comment by OpportunityLiu** [comment]
@xioxin 把数据库删掉了，发个版本试试？

**Comment by xioxin** [comment]
吧数据库删掉, 不要自动下载. 用户手动点更新下载
移除 omnibox 相关代码.
移除 右键菜单编辑tag 的代码.

不要有任何引导用户到e站的功能

**Comment by xioxin** [comment]
可以尝试, 过不过google说多次被下架可能导致封号, 那个google账号是我的主账号
如果这次上架后再被下架就不再尝试了.

**Comment by OpportunityLiu** [comment]
> 移除 右键菜单编辑tag 的代码.

这个不是导到e站吧。。

**Comment by OpportunityLiu** [comment]
> ![image](https://user-images.githubusercontent.com/5716100/64075196-ca984800-cce7-11e9-958b-cd539868c6b8.png)

这个全文在哪里？我仔细研究研究

**Comment by xioxin** [comment]
是不是导入e站, 编辑网站也有色情内容啊

**Comment by xioxin** [comment]
Dear Developer, Your Google Chrome item, "EhSyringe," with ID: mbhdcfeopadbmjnlbpcallmalcefnbbb did not comply with our policies and was removed from the Google Chrome Web Store. Your item did not comply with the following section of our policy: We don't allow content that contains nudity, graphic sex acts, or sexually explicit material. We also don't allow content that drives traffic to commercial pornography sites. Google has a zero-tolerance policy against child pornography. If we become aware of content with child pornography, we will report it to the appropriate authorities and delete the Google Accounts of those involved with the distribution. If you'd like to re-submit your item, please make the appropriate changes to the item so that it complies with our policies, then re-publish it in your developer dashboard. Please reply to this email for issues regarding this item removal. *Please keep in mind that your re-submitted item will not be immediately published live in the store. All re-submitted items undergo a strict compliance review and will be re-published if the item passes review. *Important Note Repeated or egregious violations in the store may result in your developer account being banned from the store. This may also result in the suspension of related Google services associated with your Google account. All re-submitted items will continue to be subject to Chrome Web Store policies and terms of service. Thank you for your cooperation, Google Chrome Web Store team --------------------------- Developer Terms of Service: https://developers.google.com/chrome/web-store/terms Program Policies: https://developers.google.com/chrome/web-store/program_policies Branding Guidelines: https://developers.google.com/chrome/web-store/branding

**Comment by OpportunityLiu** [comment]
按照谷歌那个说明，咋搞都是要被ban的。。。

https://developer.chrome.com/webstore/rating

把ominbox删了试试，不行就算了。右键编辑这个都不要，那是把整个项目的意义都给否定了。。

**Comment by OpportunityLiu** [comment]
然后改成“非公开”吧

**Comment by xioxin** [comment]
你可以自己注册个账号缴费发布. 我可不想冒险

**Comment by OpportunityLiu** [comment]
我连FF都不怎么用。。。

**Comment by xioxin** [comment]
未翻译标签 点击在介绍中有编辑器入口.

**Comment by wialny** [comment]
以前几天才强制关闭插件一次, 前几天天天都会被强制关闭, 这两天一天内被强制关闭好几次了. 
chrome会不会太霸道了啊, 我用什么插件也要它管吗? 同命相连的还有P站插件, 也是每天都提示我有害要关闭

**Comment by xioxin** [comment]
你可以考虑安装 dev版 Chrome 这个版本不会提示

发自我的iPhone

**Comment by OpportunityLiu** [comment]
你可以安装edge。。。

**Comment by wialny** [comment]
之前用邮件回复的内容好像没显示出来
总之感谢楼上两位的建议

**Comment by Mapaler** [comment]
你可以安装Firefox
